#!/usr/bin/bash
##Idea is that a persons github profile repo should be setup with a
##github action that runs this wakatime-stats repo and this bash script gets
##executed

##TODO how to get githubs secret repo env variables into bash variable?
##I guess it is just a normal exported env. variable so this might
##actually work
##The user would need to set a github action secret from the profile
##repos settings and name it 'WAKATIME_API_KEY'
##
##TODO how to get jq installed on ubunut-latest from github action? => use
##docker
declare wakaKey="$WAKATIME_API_KEY"
declare stuff="No sir"

#declare dataRaw=$(curl https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=$wakaKey | jq '.')

declare text=$(cat templates/preTemplateReadme.md.tpl)
##TODO create zet about this echo issue
#https://www.baeldung.com/linux/variable-preserve-linebreaks
##FX ONE: to preserve linebreaks you need to use a here-string
#cat <<<$text
##FIXME echo removes linebreak, because $IFS includes whitespace:
##spaces,tabs, newslines
#echo $text
##FIX TWO:  the shell treats quoted variables as one single argument.
##FIXME how to use sed directly on the text variable without cat/echo
echo "$text" | sed "s|<!--HERE-->|"$stuff"|g" > "$PWD/templates/README.md.tpl"

##TODO The current templates/files are used for testing, later when I
##I got a docker image and github action I need to implement it in this
##script so that it actually targets the files in the github profile
##TODO use jq to get all the data, for every title with some stats that
##you fetch from wakas api like:
## Editors, Languages etc. now have a env. variable that people have to place
## in their preTemplatesReadme.md.tpl wherever they see fit
##TODO create docker image on hub.docker.com that uses the env. I need to
##be able to run wakatime-stats
##TODO create github action that gets listed on marketplace, I guess?
##Write README.md on how to configure and setup this repo to be able to
##use it
##TODO since readme-scribe already uses a template and I can't add
##any hidden comments because readme-scribe will delete them when it runs.
##Which in turn willl make direct changes from this script on the readme-scribe template
##impossible.
##My idea is to have a pre-template which than writes and updates the
##readme-scribe template which than runs and updates the real README.md
##define the pre-template.
