#!/usr/bin/bash
##Idea is that a persons github profile repo should be setup with a
##github action that runs this wakatime-stats repo and this bash script gets
##executed

##TODO how to get githubs secret repo env variables into bash variable?
##I guess it is just a normal exported env. variable so this might
#actually work
##The user would need to set a github action secret from the profile
#repos settings and name it 'WAKATIME_API_KEY'
#
#TODO how to get jq installed on ubunut-latest from github action?
declare wakaKey=$WAKATIME_API_KEY

declare dataRaw=$(curl https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=$wakaKey | jq '.')
