name: Update README                                                             
                                                                                
on:                                                                             
  push:                                                                         
  schedule:                                                                     
    # runs once per day at midnight                                             
    - cron: "0 0 * * *"                                                         
                                                                                
jobs:                                                                           
  readme-scraper:                                                                   
    runs-on: ubuntu-latest                                                      
                                                                                
    steps:                                                                      
      - name: Checkout Repository                                               
        uses: actions/checkout@v2                                               
        with:                                                                   
          ref: main                                                             
                                                                                
      - name: Render Template                                                   
        uses: simonwoodtli/readme-scraper@main
        env:                                                                    
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}                    
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:                                                                   
          template: "templates/preTemplateReadme.md.tpl"                                   
          writeTo: "templates/README.md.tpl"                                                  
                                                                                
      - name: Push                                                              
        run: |                                                                  
          git config user.name readme-bot 🤖                                 
          git config user.email actions@github.com                              
          git add .                                                             
          git commit -m "📝 TEST: update auto-generated README.md"                    
          git push origin main     
