## Name of the Workflow
name: CI to update github profile README.md                                              
## Events to trigger Action:
on:                                                                             
  push:                                                                         
  schedule:                                                                     
    # runs once per day at midnight                                             
    - cron: "0 0 * * *"                                                         
                                                                                
## Jobs groups a set of actions to get executed
jobs:                                                                           
  ## Name of first job/group with its actions
  build:                                                                   
    runs-on: ubuntu-latest                                                      
    container:
      image: simonwoodtli/readme-scraper:latest
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}                    
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        MY_SECRET: ${{ secrets.MY_SECRET }}
      #options: -v ${{ github.workspace }}:/root

    ## actual actions
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2

        - name: echo stuff
          run: |
            echo variable value is $MY_SECRET
            echo 0
            ls /root
            echo 1
            pwd
            echo 2
            ls /__w/readme-scraper/readme-scraper
            echo 3
            cat /root/readme-scraper
            #rm /root/readme-scraper # temporarily so I can test if everything works
            #ls /root
        - name: fetch Script
          run: |
            echo y
            mkdir -p /root/.local/bin
            echo 0
            ln -sf /__w/readme-scraper/readme-scraper/readme-scraper /root/.local/bin
            echo 1
            readme-scraper /__w/readme-scraper/readme-scraper/templates/preTemplateReadme.md.tpl /__w/readme-scraper/readme-scraper/templates/README.md.tpl
            echo 2
            cat /__w/readme-scraper/readme-scraper/templates/README.md.tpl
            #wget https://raw.githubusercontent.com/SimonWoodtli/readme-scraper/main/readme-scraper -P /root/.local/bin
            #chmod u+x /__w/root/.local/bin/readme-scraper


      ## if changes get made to the script this will always fetch the
      ## newest version. If you fetch script from within Dockerfile you need to
      ## update the container and push it to registry each time you do make
      ## changes to the script.
      #- name: Exec Script
      #    run: |
      #      find . -type f -name 'readme-scraper'
      #      cat /__w/root/.local/bin/readme-scraper
      #      readme-scraper /root/templates/preTemplateReadme.md.tpl /root/templates/README.md.tpl
      #
      #  - name: echo template
      #    run: cat /root/templates/README.md.tpl

      ## run docker with `readme-scraper` script
      #- name: Run Docker container to render template to README.md.tpl
      ## mount github repo content to /root within docker
      ## pass env variables/secrets into docker
            ##FIXME docker-run-action can't pass secrets to docker
            ## container, either don't use it or try it with Dockerfile
            ## and put the env. variables in there before building
            ## container
            #--env my_secret=${{ env.MY_SECRET }}
            #--env my_secret=${{ secrets.MY_SECRET }}
            ##TODO!!!! use a Dockerfile and at build time pass in the
            #env. variables this action does not support this feature!
            ## exec script
            #readme-scraper /root/templates/preTemplateReadme.md.tpl /root/templates/README.md.tpl
            #echo readme-template
            #cat /root/templates/README.md.tpl

# - name: check content
# run: |
# echo template
# cat /root/templates/README.md.tpl
# echo pretemplate
# cat /root/templates/preTemplateReadme.md.tpl

        #with:                                                                   
          #template: "templates/preTemplateReadme.md.tpl"                                   
          #writeTo: "templates/README.md.tpl"                                                  
                                                                                
# - name: Push
# run: |
# git config user.name readme-bot 🤖
# git config user.email actions@github.com
# git add .
# git commit -m "📝 TEST: update auto-generated README.md"
# git push origin main
