name: Update README                                                             
                                                                                
on:                                                                             
  push:                                                                         
  schedule:                                                                     
    # runs once per day at midnight                                             
    - cron: "0 0 * * *"                                                         
                                                                                
jobs:                                                                           
  readme-scraper:                                                                   
    runs-on: ubuntu-latest                                                      
                                                                                
    steps:                                                                      
      ## make githubs repo content available to docker
      - name: Checkout Repository                                               
        uses: actions/checkout@v2                                               
        with:                                                                   
          ref: main                                                             

                                                                                
      ## run docker with `readme-scraper` script
      - name: Run Docker container to render template to README.md.tpl
        container:
          image: simonwoodtli/readme-scraper:latest
      ## mount github repo content to /root within docker
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}                    
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            MY_SECRET: ${{ secrets.MY_SECRET }}
          options: -v ${{ github.workspace }}:/root
        steps:
          - uses: actions/checkout@v2
          - name: run echo
            run: echo "variable value is $MY_SECRET"
      ## pass env variables/secrets into docker
            ##FIXME docker-run-action can't pass secrets to docker
            ## container, either don't use it or try it with Dockerfile
            ## and put the env. variables in there before building
            ## container
            #--env my_secret=${{ env.MY_SECRET }}
            #--env my_secret=${{ secrets.MY_SECRET }}
            ##TODO!!!! use a Dockerfile and at build time pass in the
            #env. variables this action does not support this feature!
            ## exec script
            #readme-scraper /root/templates/preTemplateReadme.md.tpl /root/templates/README.md.tpl
            #echo readme-template
            #cat /root/templates/README.md.tpl

# - name: check content
# run: |
# echo template
# cat /root/templates/README.md.tpl
# echo pretemplate
# cat /root/templates/preTemplateReadme.md.tpl

        #with:                                                                   
          #template: "templates/preTemplateReadme.md.tpl"                                   
          #writeTo: "templates/README.md.tpl"                                                  
                                                                                
# - name: Push
# run: |
# git config user.name readme-bot 🤖
# git config user.email actions@github.com
# git add .
# git commit -m "📝 TEST: update auto-generated README.md"
# git push origin main
