name: Update README                                                             
                                                                                
on:                                                                             
  push:                                                                         
  schedule:                                                                     
    # runs once per day at midnight                                             
    - cron: "0 0 * * *"                                                         
                                                                                
jobs:                                                                           
  readme-scraper:                                                                   
    runs-on: ubuntu-latest                                                      
                                                                                
    steps:                                                                      
      ## make githubs repo content available to docker
      - name: Checkout Repository                                               
        uses: actions/checkout@v2                                               
        with:                                                                   
          ref: main                                                             
                                                                                
      ## run docker with `readme-scraper` script
      - name: Run Docker container to render template to README.md.tpl
        uses: addnab/docker-run-action@v3
      ## pass env variables/secrets into docker
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}                    
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          image: simonwoodtli/readme-scraper:latest
      ## mount github repo content to /root
          options: -v ${{ github.workspace }}:/root
          run: |
            ## download script
            wget https://raw.githubusercontent.com/SimonWoodtli/readme-scraper/main/readme-scraper
            ## give permissions
            chmod u+x readme-scraper
            ## create ~ bin
            mkdir -p /root/.local/bin
            ## move script
            mv readme-scraper /root/.local/bin/readme-scraper
            ## test
            ls /root
            echo base
            cat /root/templates/preTemplateReadme.md.tpl
            echo more base
            cat /root/readme-scraper/templates/preTemplateReadme.md.tpl
            ## exec script
            readme-scraper

      - name: check content
        run: cat templates/README.md.tpl

        #with:                                                                   
          #template: "templates/preTemplateReadme.md.tpl"                                   
          #writeTo: "templates/README.md.tpl"                                                  
                                                                                
# - name: Push
# run: |
# git config user.name readme-bot 🤖
# git config user.email actions@github.com
# git add .
# git commit -m "📝 TEST: update auto-generated README.md"
# git push origin main
