name: Update README                                                             
                                                                                
on:                                                                             
  push:                                                                         
  schedule:                                                                     
    # runs once per day at midnight                                             
    - cron: "0 0 * * *"                                                         
                                                                                
jobs:                                                                           
  readme-scraper:                                                                   
    runs-on: ubuntu-latest                                                      
                                                                                
    steps:                                                                      
      ## make githubs repo content available to docker
      - name: Checkout Repository                                               
        uses: actions/checkout@v2                                               
        with:                                                                   
          ref: main                                                             
                                                                                
      ## run docker with `readme-scraper` script
      - name: Run Docker container to render template to README.md.tpl
        uses: addnab/docker-run-action@v3
      ## pass env variables/secrets into docker
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}                    
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        with:
          image: simonwoodtli/readme-scraper:latest
      ## mount github repo content to /root within docker
          options: |
            -v ${{ github.workspace }}:/root
            --env MY_SECRET=$secrets.MY_SECRET

          run: |
            ##TODO copy /root/readme-script to ~/.local/bin as it's
            #already there no need to download it with wget
            ## download script
            wget https://raw.githubusercontent.com/SimonWoodtli/readme-scraper/main/readme-scraper
            ## give permissions
            chmod u+x readme-scraper
            ## create ~ bin
            mkdir -p /root/.local/bin
            ## move script
            mv readme-scraper /root/.local/bin/readme-scraper
            ## test
            echo "MY_SECRET has value: $MY_SECRET"
            ## exec script
            #readme-scraper /root/templates/preTemplateReadme.md.tpl /root/templates/README.md.tpl
            #echo readme-template
            #cat /root/templates/README.md.tpl

      - name: check content
        run: |
          echo template
          cat /root/templates/README.md.tpl
          echo pretemplate
          cat /root/templates/preTemplateReadme.md.tpl

        #with:                                                                   
          #template: "templates/preTemplateReadme.md.tpl"                                   
          #writeTo: "templates/README.md.tpl"                                                  
                                                                                
# - name: Push
# run: |
# git config user.name readme-bot 🤖
# git config user.email actions@github.com
# git add .
# git commit -m "📝 TEST: update auto-generated README.md"
# git push origin main
